name: ${APP_NAME}

services:
  db:
    image: ${APP_NAME}/postgres:latest
    build:
      context: ./
      dockerfile: Containerfile.db
    restart: always
    ports:
      - name: db
        host_ip: 127.0.0.1
        published: 5432
        target: 5432
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

  db-manager:
    image: dpage/pgadmin4:9.8.0
    restart: always
    ports:
      - name: db-manager
        host_ip: 127.0.0.1
        published: 4444
        target: 80
    networks:
      - app-network
    volumes:
      - db-manager_data:/var/lib/pgadmin
    env_file:
      - .env.db-manager
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  server:
    image: ${APP_NAME}/spring:latest
    build:
      context: ./
      dockerfile: Containerfile.prod
    #   dockerfile: Containerfile.dev
    # volumes:
    #   - .:/app
    restart: always
    # ports:
    #   - name: server
    #     host_ip: 127.0.0.1
    #     published: 7700
    #     target: 7700
    networks:
      - app-network
    env_file:
      - .env.server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7700/health"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
    deploy:
      replicas: 3
    depends_on:
      db:
        condition: service_healthy
      # db-manager:
      #   condition: service_healthy

  webserver:
    image: ${APP_NAME}/nginx:latest
    build:
      context: ./
      dockerfile: Containerfile.nginx
    ports:
      - host_ip: 127.0.0.1
        published: 4000
        target: 443
        app_protocol: https
    networks:
      - app-network
    depends_on:
      server:
        condition: service_healthy

volumes:
  db_data:
  db-manager_data:

networks:
  app-network:
