worker_processes auto;

events {
  worker_connections 1024;
}

http {
  upstream server {
    least_conn;
    server server:7700;
  }

  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/ca-certificates/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ca-certificates/nginx-selfsigned.key;

    location / {
      proxy_pass http://server;
    }
  }
}